<a href="https://colab.research.google.com/github/suvam23/np03cs4a240165_5CS037_Worksheet1/blob/main/Suvam_Pant_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Problem - 1: Array Creation:

In [5]:
import numpy as np

# 1
arr = np.empty((2,2))
print("Empty 2x2:\n", arr)

Empty 2x2:
 [[4.99198195e-315 0.00000000e+000]
 [5.04772904e-038 2.26334694e-076]]


In [6]:
# 2
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
# 3
arr = np.full((3,3), 1)
print("\nFull array :\n", arr)


Full array :
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
# 4
arr_given = np.array([[1,2,3],[4,5,6]])
arr_zero_like = np.zeros_like(arr_given)
print("\nZeros like:\n", arr_zero_like)


Zeros like:
 [[0 0 0]
 [0 0 0]]


In [11]:
# 5
arr_one_like = np.ones_like(arr_given)
print("\nOnes like:\n", arr_one_like)


Ones like:
 [[1 1 1]
 [1 1 1]]


In [13]:
# 6
new_list = [1,2,3,4]
arr_from_list = np.array(new_list)
print("\nList to array:\n", arr_from_list)


List to array:
 [1 2 3 4]


Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

In [14]:
# 1
print("10–49:\n", np.arange(10,50))

10–49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
# 2
print("\n3x3 matrix:\n", np.arange(9).reshape(3,3))


3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
# 3
print("\nIdentity:\n", np.eye(3))



Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
# 4
arr = np.random.random(30)
print("\nMean:", arr.mean())


Mean: 0.47833332874449125


In [18]:
# 5
arr10 = np.random.random((10,10))
print("\nMin:", arr10.min(), "Max:", arr10.max())


Min: 0.001177236711637164 Max: 0.9840037376085777


In [19]:
# 6
arr6 = np.zeros(10)
arr6[4] = 1
print("\nReplace 5th:\n", arr6)


Replace 5th:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [20]:
# 7
arr7 = np.array([1,2,0,0,4,0])
print("\nReverse:\n", arr7[::-1])


Reverse:
 [0 4 0 0 2 1]


In [21]:
# 8
border = np.ones((5,5))
border[1:-1,1:-1] = 0
print("\nBorder:\n", border)



Border:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
# 9
check = np.zeros((8,8))
check[1::2, ::2] = 1
check[::2, 1::2] = 1
print("\nCheckerboard:\n", check)


Checkerboard:
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:

In [23]:
#3

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

print("Add:\n", x+y)
print("\nSubtract:\n", x-y)
print("\nMultiply by 3:\n", x*3)
print("\nSquare:\n", x**2)

print("\nDot v·w =", np.dot(v,w))
print("Dot x·v =", np.dot(x,v))
print("Dot x·y =\n", np.dot(x,y))

print("\nConcat x & y (rows):\n", np.concatenate((x,y),axis=0))
print("\nConcat v & w (cols):\n", np.vstack((v,w)))

# Error explanation
try:
    print(np.concatenate((x,v)))
except:
    print("\nERROR: x is 2D and v is 1D so shapes do not match.")


Add:
 [[ 6  8]
 [10 13]]

Subtract:
 [[-4 -4]
 [-4 -3]]

Multiply by 3:
 [[ 3  6]
 [ 9 15]]

Square:
 [[ 1  4]
 [ 9 25]]

Dot v·w = 219
Dot x·v = [29 77]
Dot x·y =
 [[19 22]
 [50 58]]

Concat x & y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concat v & w (cols):
 [[ 9 10]
 [11 12]]

ERROR: x is 2D and v is 1D so shapes do not match.


Problem - 4: Matrix Operations:

In [24]:
#1
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
result = A.dot(A_inv)
print(result)

[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [27]:
#2
AB = A.dot(B)
BA = B.dot(A)

print("AB =\n", AB)
print("BA =\n", BA)

AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]


In [26]:
#3
left_side = (A.dot(B)).T
right_side = B.T.dot(A.T)

print("Left Side (AB)^T =\n", left_side)
print("Right Side B^T A^T =\n", right_side)

Left Side (AB)^T =
 [[23 51]
 [13 29]]
Right Side B^T A^T =
 [[23 51]
 [13 29]]


In [29]:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = A_inv.dot(B)
print("Solution:", X)

Solution: [ 2.  1. -2.]


Experiment: How Fast is Numpy?

In [32]:
import time

# 1. ELEMENT-WISE ADDITION
# Python lists
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
list_add = [list1[i] + list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Addition Time:", end - start, "seconds")


# NumPy arrays
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
arr_add = arr1 + arr2
end = time.time()

print("NumPy Addition Time:", end - start, "seconds")


# 2. ELEMENT-WISE MULTIPLICATION
# Python lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(1_000_000)]
end = time.time()

print("Python List Multiplication Time:", end - start, "seconds")


# NumPy
start = time.time()
arr_mul = arr1 * arr2
end = time.time()

print("NumPy Multiplication Time:", end - start, "seconds")



# 3. DOT PRODUCT
# Python list dot product
start = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(1_000_000))
end = time.time()

print("Python List Dot Product Time:", end - start, "seconds")


# NumPy dot product
start = time.time()
arr_dot = np.dot(arr1, arr2)
end = time.time()

print("NumPy Dot Product Time:", end - start, "seconds")


# 4. MATRIX MULTIPLICATION
# Python lists
mat1 = [[i for i in range(1000)] for _ in range(1000)]
mat2 = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()

# Manual matrix multiplication (slow)
result = [[sum(mat1[i][k] * mat2[k][j] for k in range(1000))
           for j in range(1000)] for i in range(1000)]

end = time.time()
print("Python List Matrix Multiplication Time:", end - start, "seconds")


# NumPy matrix multiplication
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

start = time.time()
C = np.dot(A, B)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start, "seconds")

Python List Addition Time: 0.12278866767883301 seconds
NumPy Addition Time: 0.0021109580993652344 seconds
Python List Multiplication Time: 0.11827588081359863 seconds
NumPy Multiplication Time: 0.002118349075317383 seconds
Python List Dot Product Time: 0.10966134071350098 seconds
NumPy Dot Product Time: 0.0018627643585205078 seconds


KeyboardInterrupt: 